### ISSUE TITLE
Fix links to authors when there is more than one

### ISSUE THREAD

**Issue by intrigus-lgtm** [kitctf/www#52]
https://kitctf.de/learning/advanced_ghidra has two authors, but does not link to any of them.
Compare with https://kitctf.de/learning/python-jails which correctly links to the author.

**Comment by Ik0ri4n** [comment]
Would require a proper yaml list and a for loop on the template. [See this example](https://stackoverflow.com/questions/15189008/how-can-i-have-multiple-authors-for-one-post-in-jekyll)
